server: 
  listen: 8000
  workers: 4

  upstreams:
    - id : node1
      url: http://localhost:8001

    - id : node2
      url: http://localhost:8002
    
  header:
    - key: x-forward-for
      value: '$ip'
    - key : Authorization
      value: 'Bearer xyz'

  rules: 
    - path : /
      upstream: 
        - node1
        - node2

    - path : /admin
      upstreams:
        - node2